from __future__ import annotations


class WarningCode:
    PDF_OPEN_FAILED = "PDF_OPEN_FAILED"
    INVALID_PAGE_RANGE = "INVALID_PAGE_RANGE"
    TEXT_EXTRACTION_FAILED = "TEXT_EXTRACTION_FAILED"
    OCR_RUNTIME_UNAVAILABLE = "OCR_RUNTIME_UNAVAILABLE"
    OCR_FAILED = "OCR_FAILED"
    OCR_CONFIDENCE_CRITICAL = "OCR_CONFIDENCE_CRITICAL"
    OCR_CONFIDENCE_WARN = "OCR_CONFIDENCE_WARN"
    OCR_EMPTY_RESULT = "OCR_EMPTY_RESULT"
    IMAGE_POSITION_MAPPING_FAILED = "IMAGE_POSITION_MAPPING_FAILED"
    IMAGE_EXTRACTION_FAILED = "IMAGE_EXTRACTION_FAILED"
    TABLE_GFM_UNSAFE_FALLBACK_HTML = "TABLE_GFM_UNSAFE_FALLBACK_HTML"
    TABLE_COMPLEXITY_HTML_FALLBACK = "TABLE_COMPLEXITY_HTML_FALLBACK"
    TABLE_COMPLEXITY_MARKDOWN_COERCED = "TABLE_COMPLEXITY_MARKDOWN_COERCED"
    TABLE_EXTRACTION_FAILED = "TABLE_EXTRACTION_FAILED"


class StructureRecoveryReason:
    RECOVERED_EXACT = "STRUCTURE_MARKER_RECOVERED_EXACT"
    RECOVERED_CONTEXT_VALIDATED = "STRUCTURE_MARKER_RECOVERED_CONTEXT_VALIDATED"
    SUPPRESSED_NO_CANDIDATE = "STRUCTURE_MARKER_SUPPRESSED_NO_CANDIDATE"
    SUPPRESSED_AMBIGUOUS = "STRUCTURE_MARKER_SUPPRESSED_AMBIGUOUS"


class StructureRecoveryStrategy:
    OCR_EXACT = "ocr_exact"
    CHILD_HEADING_CONTEXT = "child_heading_context"
    PARENT_HEADING_CONTEXT = "parent_heading_context"
    SIBLING_SEQUENCE_CONTEXT = "sibling_sequence_context"
    PREVIOUS_SIBLING_CONTEXT = "previous_sibling_context"


class ImageExcludeReason:
    TINY_DECORATIVE = "TINY_DECORATIVE"
    REPEATED_SMALL_DECORATIVE = "REPEATED_SMALL_DECORATIVE"
    DECORATIVE = "DECORATIVE"


class ImageClassification:
    STRUCTURE_MARKER = "STRUCTURE_MARKER"


class TableReason:
    AMBIGUOUS_GRID = "AMBIGUOUS_GRID"
    SPARSE_LAYOUT = "SPARSE_LAYOUT"
    HEADER_FRAGMENTED = "HEADER_FRAGMENTED"
    LOW_DATA_DENSITY = "LOW_DATA_DENSITY"
    MULTILINE_CELL = "MULTILINE_CELL"


class TableModeEmission:
    HTML = "html"
    GFM = "gfm"
    MARKDOWN = "markdown"


class TableDecisionReason:
    BLOCK_OVERLAP_SUPPRESSION = "BLOCK_OVERLAP_SUPPRESSION"
    NEAR_DUPLICATE_CAPTION = "NEAR_DUPLICATE_CAPTION"
